services:
  - type: web
    name: elon-bot-encrypted
    env: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm install
    startCommand: npm run encrypted
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RATE_LIMIT
        value: 100
      - key: REPORT_HOUR
        value: 16
      - key: REPORT_MINUTE
        value: 30
      - key: TIMEZONE
        value: America/New_York 